# Generated by Django 5.1.3 on 2024-11-27 21:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='transcription.emergencysession')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('summary_text', models.TextField()),
                ('sender', models.CharField(default='Unknown', max_length=100)),
                ('receiver', models.CharField(default='Unknown', max_length=100)),
                ('category', models.CharField(default='General', max_length=100)),
                ('prioritized', models.BooleanField(default=False)),
                ('suggested_question', models.TextField(default='No suggested question provided.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_marked', models.BooleanField(default=False)),
                ('transcription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='transcription.transcription')),
            ],
        ),
    ]
