# Generated by Django 5.1.3 on 2024-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
