# Generated by Django 5.1.3 on 2024-11-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_transcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencysession',
            name='summary',
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='transcription.transcription')),
            ],
        ),
    ]
