# Generated by Django 5.1.3 on 2024-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_remove_emergencysession_summary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='summary',
            name='priority',
            field=models.CharField(default='Low', max_length=50),
        ),
        migrations.AddField(
            model_name='summary',
            name='receiver',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='summary',
            name='sender',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
