# Generated by Django 5.1.3 on 2024-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_summary_category_summary_priority_summary_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='suggested_question',
            field=models.TextField(default='No suggested question provided.'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='receiver',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='sender',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
